/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * To learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.4/samples
 */

plugins {
    `java-gradle-plugin`
    `maven-publish`
    id("com.diffplug.spotless") version "6.23.3"
    checkstyle
}

gradlePlugin {
    plugins {
        create("gradleBuildToolsPlugin") {
            id = "top.claws.gradle-build-tools"
            implementationClass = "top.claws.GradleBuildToolsPlugin"
        }
    }
}

checkstyle {
    isIgnoreFailures = false
    configFile = file("${project.rootDir}/src/main/resources/checkstyle.xml")
    configProperties["checkstyle.suppression.filter"] = file("${project.rootDir}/src/main/resources/suppressions.xml")
}

spotless {
    format("misc") {
        target("*.gradle", ".gitattributes", ".gitignore")
        trimTrailingWhitespace()
        indentWithTabs()
        endWithNewline()
    }
    java {
        googleJavaFormat("1.17.0").aosp().reflowLongStrings().skipJavadocFormatting();
        formatAnnotations()
        licenseHeader("/* (C)\$YEAR */")
    }
}

group = "top.claws"
version = "1.0"

repositories {
    mavenLocal()
    mavenCentral()
}

dependencies {
    implementation("com.diffplug.spotless:spotless-plugin-gradle:6.23.3")
    // https://mvnrepository.com/artifact/io.freefair.gradle/lombok-plugin
    implementation("io.freefair.gradle:lombok-plugin:8.4")
}
